name: Infinite Dine List
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4991
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#48b548'
    - '#ffffff'
    - '#9eb2a3'
    - '#cadfcb'
    - '#00aa00'
  brandStrength: 0.15491699334234
  lightness: 0.1943268810864538
  saturation: 0.6444622627459466
  rhythmicContrast: 0.5763226880226284
purpose: []
